export default {
  "brand": "text-text-brand",
  "disabled": "text-text-disabled",
  "error": "text-text-error",
  "infos": "text-text-infos",
  "primary": "text-text-primary",
  "primary-fixed": "text-text-primary-fixed",
  "primary-inverse": "text-text-primary-inverse",
  "primary-inverse-fixed": "text-text-primary-inverse-fixed",
  "promotion": "text-text-promotion",
  "secondary": "text-text-secondary",
  "secondary-inverse": "text-text-secondary-inverse",
  "secondary-inverse-fixed": "text-text-secondary-inverse-fixed",
  "success": "text-text-success",
  "tertiary": "text-text-tertiary",
  "tertiary-inverse": "text-text-tertiary-inverse",
  "tertiary-inverse-fixed": "text-text-tertiary-inverse-fixed",
  "warning": "text-text-warning",
};
